### ISSUE TITLE
Pass All testdata of the official monorepo

### ISSUE THREAD

**Issue by Ajwah** [cabbage-ex/gherkin#18]
This implementation fails to parse some of the [testdata of the official monorepo](https://github.com/cucumber/cucumber/tree/master/gherkin/testdata). 
For instance, when I try to parse [complex_background.feature](https://github.com/cucumber/cucumber/blob/master/gherkin/testdata/good/complex_background.feature), I get:

```shell
** (RuntimeError) Unexpected line: Examples:
    (gherkin 2.0.0) lib/gherkin/parsers/rule_parser.ex:43: Gherkin.Parsers.RuleParser.build_rule/2
    (gherkin 2.0.0) lib/gherkin/parsers/feature_parser.ex:51: Gherkin.Parsers.FeatureParser.build_feature/2
    (elixir 1.10.1) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
```

**Comment by revati** [comment]
Yes im aware. i have started full rewrite based on official testdata. There is many inconsitancies in current implementation, largest being multilanguage. 
But sadly my health has declined over few last months, so i have not had time to put needed time into it :|

**Comment by Ajwah** [comment]
> But sadly my health has declined over few last months

I am sad to hear that :(

I recently have [implemented a gherkin parser](https://github.com/Ajwah/ex-gherkin). How feasible would it be to retrofit for Cabbage? If the current implementation of `cabbage-ex/gherkin` parses out an AST, then it would be a matter of converting my AST to yours. I have an example [here](https://github.com/Ajwah/ex-gherkin/blob/master/test/parser_test.exs#L44) where I am converting my AST to the `ndjson` format of the official repo to compare to the `ndjson`-files generated by the official repo, such as these [ones](https://github.com/Ajwah/ex-gherkin/tree/master/test/support/testdata/full_features)
